# Generated by Django 4.0.6 on 2022-07-09 05:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee_model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('stack', models.CharField(max_length=50)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
